savePrefix: ""

enableGlobalVirtualStore: true

packages:
  - apps/*
  - configs/*
  - libs/*
  - tools/*

catalogMode: prefer

catalog:
  "@clack/prompts": 1.7.0
  "@types/node": 26.1.1
  tsdown: 0.22.5
  tsx: 4.23.0
  typescript: 6.0.3
  zod: 4.4.3

allowBuilds:
  esbuild: true
