savePrefix: ""

enableGlobalVirtualStore: true

packages:
  - apps/*
  - configs/*
  - libs/*
  - docker-libs/*
  - node-libs/*
  - tools/*

catalogMode: prefer

catalog:
  "@clack/prompts": 1.7.0
  "@types/node": 26.1.1
  tsdown: 0.22.9
  tsx: 4.23.1
  typescript: 6.0.3
  zod: 4.4.3

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - yuku-parser

overrides:
  "yuku-parser": 0.6.12
